// Site config schema — WRKS "bill-fanter" template.
//
// Declares which PAGES + which SECTIONS within each page make up
// this specific user's site. Generated by the WRKS Studio curation
// pass (Haiku, ~3s) BEFORE the copy pass runs — see
// project_generation_theater_architecture.md.
//
// The template's .astro page files read from this config and
// conditionally render sections:
//     {siteConfig.home.sections.includes("hero") && <Hero />}
//
// The AI picks a subset — not all pages, not all sections. What's
// picked is what best serves this specific client's business_type,
// primary_goal, and brief.

export type PageId =
  | 'home'
  | 'about'
  | 'masterclass'
  | 'community'
  | 'free-watchlist'
  | 'webinar'
  | 'watch-webinar'
  | 'blog'
  | 'student-comments'
  | 'contact'
  | 'booking'
  | 'guide'
  | 'training'
  | 'watchlist-confirmed'
  | 'privacy-policy'
  | 'terms-conditions'
  | 'refund-policy'
  | '404';

// Section IDs match the components/sections/ files + the keys in
// content.schema.ts.
export type SectionId =
  | 'hero'
  | 'aboutBill'
  | 'closing'
  | 'community'
  | 'communityPricing'
  | 'effortlessStrategy'
  | 'helpGrid'
  | 'heroSplit'
  | 'megaBento'
  | 'reviews'
  | 'spotlight'
  | 'videoTestimonials'
  | 'watchlist'
  | 'youtubeCta';

export type PageComposition = {
  sections: SectionId[]; // ordered — render order matters
};

export type SiteConfig = {
  // Ordered list of pages included in THIS user's site. Order dictates
  // both the theater sequence AND the site's IA (nav order).
  pages: PageId[];
  // Composition per included page. Only pages listed in `pages` need
  // an entry here.
  compositions: Partial<Record<PageId, PageComposition>>;
};
